#!/usr/bin/env python3
"""Generate one UI-launchable task per page from the master page-audit task.

The Playground cannot pass harbor's `extra_instruction_paths`, so a multi-page
task launched from the UI would have no page assigned. This bakes each page brief
into its own task directory, so all three appear in the Web task picker.

These directories are GENERATED — do not hand-edit them. Edit the master task
(`web_infobric-page-audit`) and re-run this script.

    uv run python application/scripts/make_page_tasks.py
"""
from __future__ import annotations

import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MASTER = REPO / "application/tasks/web_infobric-page-audit"
TASKS = REPO / "application/tasks"

# generated folder suffix -> (page brief file, task.toml name, human title)
PAGES = {
    "homepage": ("homepage.md", "application/infobric-audit-homepage", "Infobric homepage"),
    "pricing": ("pricing.md", "application/infobric-audit-pricing", "Infobric pricing page"),
    "tier-page": ("tier_page.md", "application/infobric-audit-tier-page", "Infobric audience page"),
}

BANNER = (
    "<!-- GENERATED by application/scripts/make_page_tasks.py — do not edit.\n"
    "     Edit application/tasks/web_infobric-page-audit/ and re-run the script. -->\n\n"
)


def main() -> None:
    if not MASTER.is_dir():
        sys.exit(f"master task not found: {MASTER}")
    master_instruction = (MASTER / "instruction.md").read_text(encoding="utf-8")

    for slug, (brief_file, task_name, title) in PAGES.items():
        out = TASKS / f"web_infobric-audit-{slug}"
        if out.exists():
            shutil.rmtree(out)
        # copy everything except the pages/ dir (the brief gets inlined instead)
        shutil.copytree(MASTER, out, ignore=shutil.ignore_patterns("pages"))

        brief = (MASTER / "pages" / brief_file).read_text(encoding="utf-8").strip()
        # The master says "the page named in the Page brief section of this prompt";
        # inline that section so the task stands alone without extra_instruction_paths.
        instruction = master_instruction.replace(
            'Review the page named in the **"Page brief"** section below, as yourself and in your\nown situation.',
            "Review the page named below, as yourself and in your own situation.\n\n" + brief,
        )
        if brief not in instruction:
            sys.exit(f"could not inline the brief for {slug}; master instruction.md changed shape")
        # No banner here: instruction.md is sent verbatim to the model.
        (out / "instruction.md").write_text(instruction, encoding="utf-8")
        (out / "GENERATED").write_text(BANNER, encoding="utf-8")

        toml = (out / "task.toml").read_text(encoding="utf-8").replace(
            'name = "application/infobric-page-audit"', f'name = "{task_name}"'
        )
        (out / "task.toml").write_text(toml, encoding="utf-8")

        (out / "README.md").write_text(
            f"# {title} — audit (generated)\n\n"
            f"**Generated** by `application/scripts/make_page_tasks.py` from\n"
            f"`application/tasks/web_infobric-page-audit/` + `pages/{brief_file}`.\n"
            f"Do not hand-edit: change the master task and re-run the script.\n\n"
            f"This variant exists so the page is launchable from the Playground UI, which\n"
            f"cannot pass harbor's `extra_instruction_paths`. For CLI runs, prefer the\n"
            f"master task with `application/scripts/make_page_jobs.py`.\n",
            encoding="utf-8",
        )
        print(f"  web_infobric-audit-{slug:<10} ← pages/{brief_file}")

    print("\nRegister any new ones in application/playground/backend/service/"
          "playground_task_registry.py, then restart the backend.")


if __name__ == "__main__":
    main()
