#!/usr/bin/env python3
"""Generate one UI-launchable task per page from the page-audit v2 master.

The Playground cannot pass harbor's `extra_instruction_paths`, so each page gets its
own task directory with the brief inlined, the page's context and inventory copied to
`input/`, the persona filter set, and a `variant.txt` marker the verifier reads.

These directories are GENERATED - do not hand-edit them. Edit the master
(`application/task-templates/web_infobric-audit-v2`) and re-run:

    uv run python application/scripts/make_audit_v2_tasks.py [--variants full,skim]

A page is generated only if `pages/<page>.md`, `pages/<page>.context.md` and
`pages/<page>.inventory.json` all exist; missing pages are listed, not failed.
"""
from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
MASTER = REPO / "application/task-templates/web_infobric-audit-v2"
TASKS = REPO / "application/tasks"
MARKER = "<!-- PAGE BRIEF -->"

# Default cohort per page: proportional to the pool's visitor-kind mix. The homepage
# is the pilot's full run; product pages default to a pilot-sized sample.
PAGE_SAMPLE = {"homepage": 1000, "fleet": 100, "driving-log": 100, "equipment": 100, "hyrma": 100}

# folder suffix -> (page_id, task.toml name, title, persona dimension filter)
PAGES = {
    "homepage": ("homepage", "application/infobric-audit-v2-homepage", "Infobric homepage", {}),
    "fleet": ("fleet", "application/infobric-audit-v2-fleet", "Infobric Fleet",
              {"deals_with_vehicles": ["Part of my job"]}),
    "driving-log": ("driving_log", "application/infobric-audit-v2-driving-log", "Electronic Driving Log",
                    {"deals_with_driving_logs": ["Part of my job"]}),
    "equipment": ("equipment", "application/infobric-audit-v2-equipment", "Infobric Equipment",
                  {"deals_with_tools_equipment": ["Part of my job"]}),
    "hyrma": ("hyrma", "application/infobric-audit-v2-hyrma", "Infobric Hyrma",
              {"works_in_rental_process": ["Part of my job"]}),
}

BANNER = (
    "<!-- GENERATED by application/scripts/make_audit_v2_tasks.py - do not edit.\n"
    "     Edit application/task-templates/web_infobric-audit-v2/ and re-run the script. -->\n\n"
)


def _generate(slug: str, page_id: str, task_name: str, title: str, dim_filter: dict, variant: str) -> Path:
    pages = MASTER / "pages"
    brief = (pages / f"{page_id}.md").read_text(encoding="utf-8").strip()
    context = (pages / f"{page_id}.context.md").read_text(encoding="utf-8")
    inventory = (pages / f"{page_id}.inventory.json").read_text(encoding="utf-8")

    suffix = "" if variant == "full" else f"-{variant}"
    out = TASKS / f"web_infobric-audit-v2-{slug}{suffix}"
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(MASTER, out, ignore=shutil.ignore_patterns("pages", "__pycache__", "README.md"))

    instruction = (MASTER / "instruction.md").read_text(encoding="utf-8")
    if MARKER not in instruction:
        sys.exit("master instruction.md has no <!-- PAGE BRIEF --> marker")
    instruction = instruction.replace(MARKER, brief)
    if variant != "full":
        extra = pages / "variants" / f"{variant}.md"
        if not extra.is_file():
            sys.exit(f"variant file missing: {extra}")
        instruction = instruction.rstrip() + "\n\n" + extra.read_text(encoding="utf-8").strip() + "\n"
    # instruction.md is sent verbatim to the model: no banner in it.
    (out / "instruction.md").write_text(instruction, encoding="utf-8")
    (out / "GENERATED").write_text(BANNER, encoding="utf-8")

    (out / "input").mkdir(exist_ok=True)
    (out / "input" / "context.md").write_text(context, encoding="utf-8")
    (out / "input" / "inventory.json").write_text(inventory, encoding="utf-8")
    (out / "input" / "variant.txt").write_text(variant + "\n", encoding="utf-8")

    toml = (out / "task.toml").read_text(encoding="utf-8").replace(
        'name = "application/infobric-audit-v2"', f'name = "{task_name}{suffix}"'
    )
    (out / "task.toml").write_text(toml, encoding="utf-8")

    strategy = json.loads((MASTER / "persona_strategy.json").read_text(encoding="utf-8"))
    strategy["dimensionFilters"] = dim_filter
    strategy["sampling"] = {
        "mode": "stratified", "fields": ["audience_group"],
        "allocation": "proportional", "sampleSize": PAGE_SAMPLE.get(slug, 100),
    }
    (out / "persona_strategy.json").write_text(json.dumps(strategy, indent=2) + "\n", encoding="utf-8")

    (out / "README.md").write_text(
        f"# {title} - page audit v2{' (' + variant + ')' if variant != 'full' else ''} (generated)\n\n"
        f"**Generated** by `application/scripts/make_audit_v2_tasks.py` from\n"
        f"`application/task-templates/web_infobric-audit-v2/` + `pages/{page_id}.*`.\n"
        f"Do not hand-edit: change the master and re-run the script.\n",
        encoding="utf-8",
    )
    return out


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n", 1)[0])
    ap.add_argument("--variants", default="full", help="comma-separated, e.g. full,skim")
    args = ap.parse_args(argv)
    variants = [v.strip() for v in args.variants.split(",") if v.strip()]

    if not MASTER.is_dir():
        sys.exit(f"master task not found: {MASTER}")
    made, skipped = [], []
    for slug, (page_id, task_name, title, dim_filter) in PAGES.items():
        needed = [MASTER / "pages" / f"{page_id}{ext}" for ext in (".md", ".context.md", ".inventory.json")]
        if not all(p.is_file() for p in needed):
            skipped.append(slug)
            continue
        for variant in variants:
            out = _generate(slug, page_id, task_name, title, dim_filter, variant)
            made.append(out.name)
            print(f"  {out.name:<40} <- pages/{page_id}.*  filter={dim_filter or 'none'}")
    if skipped:
        print(f"  skipped (no brief/context/inventory yet): {', '.join(skipped)}")
    print("\nRegister any new ones in application/playground/backend/service/"
          "playground_task_registry.py, then restart the backend.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
