#!/usr/bin/env python3
"""Generate one task variant per web agent from a master web task.

Each web agent needs its own Docker image, and the image comes from
``[environment].definition`` in task.toml — which lives in the task, not the job
recipe. Harbor's staging helper (web_task_environment.py) only rewrites that line
for the CLI-harness agents, so comparing the four web agents needs one task
directory each. This generates them from a single master so the instruction,
rubric and verifier stay in one place.

    uv run python application/scripts/make_agent_variants.py \
        --master application/tasks/web_infobric-audit-homepage \
        --agents browseruse cocoa

Generated dirs are build output — edit the master and re-run.
"""
from __future__ import annotations

import argparse
import re
import shutil
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]

# suffix -> (image definition, harbor agent name, note)
VARIANTS = {
    "playwright": ("application/shared-web-playwright", "persona-openhands-sdk", "DOM only"),
    "browseruse": ("application/shared-web-browser-use", "persona-browser-use", "DOM + optional screenshots"),
    "cocoa": ("application/shared-web-cocoa", "persona-cocoa", "DOM + screenshots + shell"),
    "cua": ("application/shared-web-cua-linux", "persona-computer-1", "screenshot every turn"),
}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--master", required=True, type=Path)
    ap.add_argument("--agents", nargs="+", default=["browseruse", "cocoa"], choices=sorted(VARIANTS))
    args = ap.parse_args()

    master = (REPO / args.master) if not args.master.is_absolute() else args.master
    if not (master / "task.toml").is_file():
        sys.exit(f"no task.toml in {master}")

    for suffix in args.agents:
        definition, agent, note = VARIANTS[suffix]
        out = master.parent / f"{master.name}-{suffix}"
        if out.exists():
            shutil.rmtree(out)
        shutil.copytree(master, out, ignore=shutil.ignore_patterns("pages", "GENERATED"))

        toml_path = out / "task.toml"
        text = toml_path.read_text(encoding="utf-8")
        text, n = re.subn(r'(^[\t ]*definition[\t ]*=[\t ]*")([^"]+)(")',
                          lambda m: m.group(1) + definition + m.group(3), text, flags=re.M)
        if n != 1:
            sys.exit(f"{suffix}: expected exactly one [environment].definition, found {n}")
        text = re.sub(r'^name = "([^"]+)"$', lambda m: f'name = "{m.group(1)}-{suffix}"', text, flags=re.M)
        toml_path.write_text(text, encoding="utf-8")

        (out / "GENERATED").write_text(
            f"Generated by application/scripts/make_agent_variants.py from {master.name}.\n"
            f"Agent: {agent}  ·  image: {definition}  ·  {note}\n"
            f"Do not hand-edit; change the master and re-run.\n", encoding="utf-8")
        print(f"  {out.name:<46} {agent:<24} {definition}")

    print("\nRegister in application/playground/backend/service/playground_task_registry.py "
          "if you want them in the UI, then restart the backend.")


if __name__ == "__main__":
    main()
